package com.example.lx.wyredpacketandroid.utils.greendaoUtil;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lx.wyredpacketandroid.utils.greendaoform.UserToken;

import com.example.lx.wyredpacketandroid.utils.greendaoUtil.UserTokenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userTokenDaoConfig;

    private final UserTokenDao userTokenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userTokenDaoConfig = daoConfigMap.get(UserTokenDao.class).clone();
        userTokenDaoConfig.initIdentityScope(type);

        userTokenDao = new UserTokenDao(userTokenDaoConfig, this);

        registerDao(UserToken.class, userTokenDao);
    }
    
    public void clear() {
        userTokenDaoConfig.clearIdentityScope();
    }

    public UserTokenDao getUserTokenDao() {
        return userTokenDao;
    }

}
